language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

services:
  - mysql

before_install:
  - mysql -e "CREATE DATABASE IF NOT EXISTS test;" -uroot

install:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit
