language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

services:
  - mysql

before_install:
  - mysql -u root -e 'create database test;'

install:
  - travis_retry composer install --no-interaction --prefer-dist

script:
  - vendor/bin/phpunit
